"""Terminal, JSON, Markdown, and SARIF 2.1.0 reporting."""

from __future__ import annotations

import json
from collections.abc import Callable
from typing import Any

from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from agentguard.models import ScanResult, Severity


def to_json(result: ScanResult) -> str:
    payload = {
        "schema_version": "1.0",
        "tool": {"name": "AgentGuard", "version": _version()},
        "scan": {
            "root": result.root.as_posix(),
            "files_scanned": result.files_scanned,
            "rules_run": result.rules_run,
            "skipped_files": result.skipped_files,
            "duration_ms": round(result.duration_ms, 2),
            "counts": result.counts(),
            "errors": result.errors,
        },
        "findings": [finding.to_dict(result.root) for finding in result.findings],
    }
    return json.dumps(payload, indent=2)


def to_markdown(result: ScanResult) -> str:
    counts = result.counts()
    rows = [
        "# AgentGuard Security Report",
        "",
        f"**Target:** `{result.root}`  ",
        f"**Files scanned:** {result.files_scanned}  ",
        f"**Findings:** {len(result.findings)} "
        f"(Critical {counts['Critical']} · High {counts['High']} · Medium {counts['Medium']} · Low {counts['Low']})",
        "",
    ]
    if not result.findings:
        rows.extend(["## Result", "", "No security findings were detected.", ""])
    for finding in result.findings:
        path = finding.location.path.relative_to(result.root).as_posix()
        rows.extend(
            [
                f"## {finding.severity.name.title()} · {finding.rule_id} · {finding.title}",
                "",
                f"**Location:** `{path}:{finding.location.line}:{finding.location.column}`  ",
                f"**Category:** {finding.category}  ",
                f"**Confidence:** {finding.confidence}",
                "",
                f"**Explanation:** {finding.explanation}",
                "",
                f"**Risk:** {finding.risk}",
                "",
                f"**Remediation:** {finding.remediation}",
                "",
            ]
        )
    if result.errors:
        rows.extend(["## Scan warnings", "", *[f"- {error}" for error in result.errors], ""])
    rows.append("_Generated by AgentGuard._")
    return "\n".join(rows)


def to_sarif(result: ScanResult) -> str:
    unique: dict[str, Any] = {}
    sarif_results: list[dict[str, Any]] = []
    level = {
        Severity.CRITICAL: "error",
        Severity.HIGH: "error",
        Severity.MEDIUM: "warning",
        Severity.LOW: "note",
    }
    for finding in result.findings:
        unique.setdefault(
            finding.rule_id,
            {
                "id": finding.rule_id,
                "name": finding.title.replace(" ", ""),
                "shortDescription": {"text": finding.title},
                "fullDescription": {"text": finding.explanation},
                "help": {"text": finding.remediation},
                "properties": {
                    "category": finding.category,
                    "security-severity": str(float(int(finding.severity) * 2.5)),
                },
            },
        )
        path = finding.location.path.relative_to(result.root).as_posix()
        sarif_results.append(
            {
                "ruleId": finding.rule_id,
                "level": level[finding.severity],
                "message": {
                    "text": f"{finding.explanation} Risk: {finding.risk} Remediation: {finding.remediation}"
                },
                "locations": [
                    {
                        "physicalLocation": {
                            "artifactLocation": {"uri": path, "uriBaseId": "%SRCROOT%"},
                            "region": {
                                "startLine": finding.location.line,
                                "startColumn": finding.location.column,
                            },
                        }
                    }
                ],
                "properties": {"severity": finding.severity.name.title(), "confidence": finding.confidence},
            }
        )
    payload = {
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "version": "2.1.0",
        "runs": [
            {
                "tool": {
                    "driver": {
                        "name": "AgentGuard",
                        "version": _version(),
                        "informationUri": "https://github.com/amic25/agentguard",
                        "rules": list(unique.values()),
                    }
                },
                "originalUriBaseIds": {"%SRCROOT%": {"uri": result.root.as_uri() + "/"}},
                "results": sarif_results,
                "invocations": [
                    {
                        "executionSuccessful": not result.errors,
                        "toolExecutionNotifications": [
                            {"message": {"text": error}, "level": "warning"} for error in result.errors
                        ],
                    }
                ],
            }
        ],
    }
    return json.dumps(payload, indent=2)


def render_terminal(result: ScanResult, console: Console | None = None) -> None:
    output = console or Console()
    colors = {
        Severity.CRITICAL: "bold red",
        Severity.HIGH: "red",
        Severity.MEDIUM: "yellow",
        Severity.LOW: "blue",
    }
    output.print(
        Panel.fit("[bold cyan]AgentGuard[/bold cyan]  AI Agent Security Scanner", border_style="cyan")
    )
    if result.findings:
        table = Table(show_lines=True, expand=True)
        table.add_column("Severity", width=9)
        table.add_column("Rule", width=7)
        table.add_column("Location", ratio=2)
        table.add_column("Finding", ratio=4)
        for finding in result.findings:
            path = finding.location.path.relative_to(result.root).as_posix()
            table.add_row(
                f"[{colors[finding.severity]}]{finding.severity.name.title()}[/]",
                finding.rule_id,
                f"{path}:{finding.location.line}",
                f"[bold]{finding.title}[/bold]\n{finding.explanation}\n[dim]Fix: {finding.remediation}[/dim]",
            )
        output.print(table)
    else:
        output.print("[bold green]✓ No findings detected.[/bold green]")
    counts = result.counts()
    output.print(
        f"\nScanned [bold]{result.files_scanned}[/bold] files with [bold]{result.rules_run}[/bold] rules in {result.duration_ms:.0f}ms · "
        f"[red]{counts['Critical']} critical[/red], [red]{counts['High']} high[/red], "
        f"[yellow]{counts['Medium']} medium[/yellow], [blue]{counts['Low']} low[/blue]"
    )
    for error in result.errors:
        output.print(f"[yellow]Warning:[/yellow] {error}")


REPORTERS: dict[str, Callable[[ScanResult], str]] = {
    "json": to_json,
    "markdown": to_markdown,
    "sarif": to_sarif,
}


def _version() -> str:
    from agentguard import __version__

    return __version__
